function createfigure(XData1, YData1, XData2, YData2, XData3, YData3, XData4, YData4, XData5, YData5, XData6, YData6, YData7, YData8, YData9, YData10)
%CREATEFIGURE(XDATA1,YDATA1,XDATA2,YDATA2,XDATA3,YDATA3,XDATA4,YDATA4,XDATA5,YDATA5,XDATA6,YDATA6,YDATA7,YDATA8,YDATA9,YDATA10)
%  XDATA1:  line xdata
%  YDATA1:  line ydata
%  XDATA2:  line xdata
%  YDATA2:  line ydata
%  XDATA3:  line xdata
%  YDATA3:  line ydata
%  XDATA4:  line xdata
%  YDATA4:  line ydata
%  XDATA5:  line xdata
%  YDATA5:  line ydata
%  XDATA6:  line xdata
%  YDATA6:  line ydata
%  YDATA7:  line ydata
%  YDATA8:  line ydata
%  YDATA9:  line ydata
%  YDATA10:  line ydata

%  Auto-generated by MATLAB on 12-Mar-2012 16:44:04

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YColor',[0.4 0.4 0.4],'XScale','log',...
    'XMinorTick','on',...
    'XColor',[0.4 0.4 0.4],...
    'Position',[0.138784773060029 0.11 0.766215226939971 0.765859950859951],...
    'FontSize',8);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[10 100000]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-70 20]);
box(axes1,'on');
hold(axes1,'all');

% Create ylabel
ylabel('Magnitude (dB)','FontSize',8);

% Create line
line(XData1,YData1,'Parent',axes1,'Visible','off','Color',[0 0 1]);

% Create hggroup
hggroup1 = hggroup('Parent',axes1,'DisplayName','Hc');

% Create line
line(XData2,YData2,'Parent',hggroup1,'Color',[0 0 1]);

% Create hggroup
hggroup2 = hggroup('Parent',axes1,'DisplayName','Hc');

% Create line
line(XData3,YData3,'Parent',hggroup2,'Color',[0 0.65 0]);

% Create hggroup
hggroup3 = hggroup('Parent',axes1,'DisplayName','Hc');

% Create line
line(XData4,YData4,'Parent',hggroup3,'Color',[1 0 0]);

% Create hggroup
hggroup4 = hggroup('Parent',axes1,'DisplayName','Hc');

% Create line
line(XData5,YData5,'Parent',hggroup4,'Color',[0 0.75 0.75]);

% Create axes
axes2 = axes('Visible','off','Parent',figure1,'YColor',[0.4 0.4 0.4],...
    'XScale','log',...
    'XMinorTick','on',...
    'XColor',[0.4 0.4 0.4],...
    'Position',[0.13 0.11 0.3875 0.4075],...
    'FontSize',8);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[10 100000]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[0 1]);
box(axes2,'on');
hold(axes2,'all');

% Create line
line(XData6,YData6,'Parent',axes2,'Visible','off','Color',[0 0 1]);

% Create hggroup
hggroup5 = hggroup('Parent',axes2,'DisplayName','Hc');

% Create line
line(XData2,YData7,'Parent',hggroup5,'Color',[0 0 1]);

% Create hggroup
hggroup6 = hggroup('Parent',axes2,'DisplayName','Hc');

% Create line
line(XData3,YData8,'Parent',hggroup6,'Color',[0 0.65 0]);

% Create hggroup
hggroup7 = hggroup('Parent',axes2,'DisplayName','Hc');

% Create line
line(XData4,YData9,'Parent',hggroup7,'Color',[1 0 0]);

% Create hggroup
hggroup8 = hggroup('Parent',axes2,'DisplayName','Hc');

% Create line
line(XData5,YData10,'Parent',hggroup8,'Color',[0 0.75 0.75]);

% Create title
title('Bode Diagram','Units','pixels','FontSize',8);

% Create xlabel
xlabel('Frequency  (rad/s)','Units','pixels','FontSize',8);

% Create legend
legend(axes1,'show');

